Feature/vectors
ivanetc/HIRenderer pull request #4
Opened 2022-04-10 16:12 UTC by KhilikEgor

2022-04-11 08:56 UTC, ivanetc requested changes

2022-04-11 08:56 UTC, ivanetc commented on Math/Vec3.cpp
> +    return {x+a.x, y+a.y, z+a.z};
Выглядит так, как будто бы мы определили унарный оператор, а вроде бы нужно определить бинарный. Странно, что оно работает, нужно бы почитать в чем разница между переопределением унарных и бинарных операторов
https://habr.com/ru/post/132014/

2022-04-11 08:56 UTC, ivanetc commented on Math/Vec3.cpp
> +    return *this;
Вообще тоже очень странно, что проходят тесты, по идее нужно еще поля переприсвоить
https://ru.stackoverflow.com/questions/173051/Перегрузка-оператора-присваивания-c

2022-04-11 08:56 UTC, ivanetc commented on tests/Math/Vec3/Vec3OperatorsTests.cpp
> +    Vec3 vec1 = original_vec;
В общем это не совсем работающий тест, у нас немного неправильно сделан оператор присваивания - я там оставил коммент.
Этот тест по сути должен проверять оператор присваивания, т.е. когда у нас есть какой-то вектор, и мы хотим потом ему присвоить значение.
А здесь работает не оператор присваивания, а так называемый "конструктор копирования"

Для того, чтобы проверить работу оператора присваивания нужно следующее:
```cpp    
Vec3 vec1 = Vec3(0,0,0);
vec1 = original_vec;
```

2022-04-11 08:56 UTC, ivanetc commented on tests/Math/Vec3/Vec3OperatorsTests.cpp
> +    std::cout << "Vec3OperatorsTests: tests completed successfully!" << std::endl;
Возможно стоит добавить тест, который бы комбинировал действия, 
было бы круто проверить что-то типа
v1 * (v2 - v3 * v4 + v5) или что-нибудь хитровыдуманное

2022-04-16 15:06 UTC, ivanetc requested changes

2022-04-16 15:06 UTC, ivanetc commented on Math/Vec3.cpp
> +    return this->z;
насколько я знаю приватные поля в классах в cpp обычно называют field_name_ с нижним подчеркиванием в конце

https://google.github.io/styleguide/cppguide.html#Variable_Names

2022-04-17 12:35 UTC, KhilikEgor commented on Math/Vec3.cpp
> +    return {x+a.x, y+a.y, z+a.z};
ok

2022-04-17 12:50 UTC, KhilikEgor commented on Math/Vec3.cpp
> +    return *this;
ok

2022-04-17 13:15 UTC, KhilikEgor commented on Math/Vec3.cpp
> +    return this->z;
ok

2022-04-17 13:32 UTC, KhilikEgor commented on tests/Math/Vec3/Vec3OperatorsTests.cpp
> +    std::cout << "Vec3OperatorsTests: tests completed successfully!" << std::endl;
ok

2022-04-17 13:34 UTC, KhilikEgor commented on tests/Math/Vec3/Vec3OperatorsTests.cpp
> +    Vec3 vec1 = original_vec;
ok

2022-04-17 13:47 UTC, ivanetc approved these changes

2022-04-17 13:48 UTC, merged